root = "."
tmp_dir = "tmp"

[build]
cmd = "make site/generate/bin"
bin = "./tmp/site/main"
include_ext = ["yml", "html", "go"]
include_file = ["catalog.yml"]
include_dir = ["templates", "internal"]
exclude_dir = ["tmp", "build", "public", "cmd/generate_readme"]
delay = 1000

[log]
time = true

[screen]
clear_on_rebuild = true