on: [push]
jobs:
  deploy:
    name: Deploy site to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: make site/generate
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          branch: main
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy build/site --project-name=${{ vars.CLOUDFLARE_PAGES_PROJECT_NAME }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}